-- treesitter based syntax highlighting
return {
    'nvim-treesitter/nvim-treesitter',
    build = function()
        require('nvim-treesitter.install').update { with_sync = true }
    end,
    config = function()
        -- TODO: optimize this so that it doesn't alwyas run on startup
        if vim.fn.executable 'gcc' ~= 1 or vim.fn.executable 'g++' ~= 1 then
            vim.notify(
                'Treesitter is disabled\n'
                    .. 'Please install gcc and g++ to enable Treesitter',
                vim.log.levels.ERROR,
                { title = 'nvpunk.plugins.treesitter' }
            )
            return
        end
        require('nvim-treesitter.configs').setup {
            ensure_installed = {
                'arduino',
                'astro',
                'bash',
                'bibtex',
                'blueprint',
                'c',
                'c_sharp',
                'clojure',
                'cmake',
                'comment',
                'commonlisp',
                'cpp',
                'css',
                'cuda',
                'dart',
                'diff',
                'dockerfile',
                'dot',
                'elixir',
                'elm',
                'erlang',
                'fennel',
                'fish',
                'foam',
                'fsh',
                'func',
                'fusion',
                'gdscript',
                'git_rebase',
                'gitattributes',
                'gitcommit',
                'gleam',
                'glimmer',
                'glsl',
                'go',
                'gomod',
                'gosum',
                'gowork',
                'graphql',
                'haskell',
                'hcl',
                'hjson',
                'hlsl',
                'html',
                'htmldjango',
                'http',
                'ini',
                'java',
                'javascript',
                'jq',
                'jsdoc',
                'json',
                'json5',
                'jsonc',
                'jsonnet',
                'julia',
                'kotlin',
                'latex',
                'llvm',
                'lua',
                'make',
                'markdown',
                'markdown_inline',
                'mermaid',
                'meson',
                'ninja',
                'nix',
                'norg',
                'ocaml',
                'ocaml_interface',
                'org',
                'perl',
                'pioasm',
                'proto',
                'pug',
                'python',
                'ql',
                'qmljs',
                'query',
                'regex',
                'rego',
                'rst',
                'ruby',
                'rust',
                'scala',
                'scheme',
                'scss',
                'slint',
                'sparql',
                'surface',
                'svelte',
                'terraform',
                'thrift',
                'tlaplus',
                'todotxt',
                'toml',
                'tsx',
                'typescript',
                'v',
                'vala',
                'verilog',
                'vim',
                'vue',
                'wgsl',
                'wgsl_bevy',
                'yaml',
                'zig',
            },
            -- sync_install = false,  -- don't peg slow systems
            highlight = {
                enable = true,
                use_languagetree = true,
                additional_vim_regex_highlighting = false,
            },
            incremental_selection = {
                enable = false,
                keymaps = {
                    init_selection = '<leader>ss',
                    node_incremental = '<Up>',
                    scope_incremental = '<S-Up>',
                    node_decremental = '<C-Up>',
                },
            },
            indent = {
                enable = true,
            },
            autopairs = {
                enable = true,
            },
            autotag = { -- this is a plugin: nvim-ts-autotag
                enable = true,
                filetypes = {
                    'html',
                    'xml',
                    'javascript',
                    'javascriptreact',
                    'typescriptreact',
                    'svelte',
                    'vue',
                    'astro',
                },
            },
        }
    end,
}
